[[kithara]]
= kithara image:https://travis-ci.org/xsc/kithara.svg?branch=master["Build Status", link="https://travis-ci.org/xsc/kithara"]
:toc: macro
:toc-title:
:toclevels: 3

*kithara* is a (limited) https://www.rabbitmq.com[RabbitMQ] client for Clojure,
based on https://github.com/jhalterman/lyra[Lyra]. Its specific scope - and
thus source of its limitations - is the simple creation of RabbitMQ-based
 consumers with appropriate recovery and retry facilities.

If you're looking for a more complete RabbitMQ library you should check out
https://github.com/michaelklishin/langohr[langohr].

== Table of Contents

toc::[]

[[usage]]
== Usage

Coming soon.

[[quickstart]]
=== Quickstart

[source,clojure]
----
(require '[kithara.core :as rabbitmq]
         '[com.stuartsierra.component :as component])

(defonce rabbitmq-consumer
  (-> (rabbitmq/consumer
        (fn [{:keys [body]}]
          (println body))
        {:as :string})
      (rabbitmq/with-queue
        "my-queue"
        {:exchange     "my-exchange"
         :routing-keys ["*.print"]})
      (rabbitmq/with-channel
        {:prefetch-count 20})
      (rabbitmq/with-connection
        {:host "rabbitmq.my-cluster.com"})))

(alter-var-root #'rabbitmq-consumer component/start)
----

[[building-a-consumer]]
== Building a Consumer

kithara is basically a toolbox with components handling RabbitMQ connection,
channel and queue setup. Here you'll see how to combine them.

[[building-the-handler]]
=== Handler

A handler is a function. It takes a single map (the message) and produces
another map (the confirmation) specifying how to react to the message, i.e.
whether to `ACK`, `NACK` or `REJECT` it.

==== Message Format

This is an example message:

[source,clojure]
----
{:channel      #object[com.sun.proxy.$Proxy1 0x17cd517c "net.jodah.lyra.config.Config@190abc2d"],
 :body         #object["[B" 0x13d05618 "[B@13d05618"],
 :body-raw     #object["[B" 0x13d05618 "[B@13d05618"],
 :properties   {...},
 :routing-key  "the-routing-key",
 :exchange     "the-exchange",
 :redelivered? false,
 :delivery-tag 33,
 :consumer-tag "kithara:96CDgYbID9a1IlDwDS"}
----

Most of the semantics should be clear, so just a few notes:

- `:body-raw` always contains a byte array with the raw payload.
- `:body` contains a potentially preprocessed payload (see
  <<message-coercion,Message Coercion>>), otherwise it's identical to
`:body-raw`.
- `:properties` represents the message's
  https://www.rabbitmq.com/releases/rabbitmq-java-client/v3.6.1/rabbitmq-java-client-javadoc-3.6.1/com/rabbitmq/client/AMQP.BasicProperties.html[`BasicProperties`].

==== Confirmation Format

The confirmation is a map describing how to react to the message that was
processed, mainly using the `:status` key which can take any of the following
values:

- `:ack` (`ACK` the message)
- `:nack` (`NACK` the message)
- `:reject` (`REJECT` the message)
- `:error` (an exception occured)
- `:done` (the message was explicitly confirmed within the handler)

`:nack`, `:reject` and `:error` also rely on the `:requeue?` key to decide
whether or not to re-add a message to the back of the queue (defaults to `true`
for `NACK`). Additionally, `:message` and `:error` can be given to augment the
log messages printed by the consumer.

An example confirmation could thus be:

[source,clojure]
----
{:status   :nack
 :requeue? false
 :message  "this is unacceptable."}
----

The reliance on pure data for message handling should make your handlers a
little more testable in the long run.

=== Base Consumer

http://xsc.github.io/kithara/kithara.core.html#var-consumer[*Documentation*]

Once your handler is ready, you can create the base consumer component. It's not
yet bound to any connection, queue or channel, it just encapsulates the handling
logic.

[source,clojure]
----
(kithara.core/consumer handler)
(kithara.core/consumer handler {... options ...})
----

Options can be used to tweak its behaviour a bit.

[[message-coercion]]
==== Message Coercion

The `:as` option specifies a coercer for the incoming payload. It can be one of
the following:

- `:bytes` (default): just use the raw byte array,
- `:string`: convert the byte array to a UTF-8 string,
- a function: apply the function to the byte array,
- any value implementing `kithara.protocols/Coercer`.

So, a consumer that prints every incoming message's `:body` as a string would
be constructed as:

[source,clojure]
----
(kithara.core/consumer
  (fn [{:keys [body]}]
    (println body)
    {:status :ack})
  {:as :string})
----

==== Default Confirmation Behaviour

If a handler does not return a map (or a map without the `:status` key) the
message will be confirmed using `ACK`. In the same vein, if the handler throws
an exception the message will be confirmed with `NACK` and requeued.

This can be adjusted using the `:default-confirmation` and `:error-confirmation`
keys, e.g.:

[source,clojure]
----
(kithara.core/consumer
  ...
  {:default-confirmation {:status :nack}
   :error-confirmation   {:status :reject}})
----

==== Consumer Name/Tag

It's often useful to be able to identify a consumer, e.g. in the RabbitMQ
management plugin displaying only the consumer tag.

You can thus either set the consumer tag explicitly (using the `:consumer-tag`
option) or you can give your consumer a name (`:consumer-name`) that will be
included in a custom, unique consumer tag chosen by kithara.

==== Low-Level Options

The options `:local?`, `:exclusive?` and `:arguments` refer to the respective
parameters in RabbitMQ's `basic.consume`.

[[channels]]
=== Channels

http://xsc.github.io/kithara/kithara.core.html#var-with-channel[*Documentation*]

Consumers have to be bound to a channel before they can be started, which
is easily achieved:

[source,clojure]
----
(kithara.core/with-channel
  consumer
  {:prefetch-count 256})
----

See the documentation for available options. You should set at least
`:prefetch-count`, though, to prevent your consumer from loading more messages
into memory than it can stomach. A shorthand for this can be found in
http://xsc.github.io/kithara/kithara.core.html#var-with-prefetch-channel[`with-prefetch-channel`].

[[queues]]
=== Queues

http://xsc.github.io/kithara/kithara.core.html#var-with-queue[*Documentation*]

Consumers need a queue to receive messages from and that queue is bound to
exchange/routing-key pairs. It can be easily set up:

[source,clojure]
----
(kithara.core/with-queue
  consumer
  "queue-name"
  {:durable?     true
   :exclusive?   false
   :auto-delete? false
   :exchange     "exchange"
   :routing-keys ["#"]})
----

If no options (see documentation) are given, the queue will not be actively
declared but expected to already exist.

There are shorthands for commonly used queue types like
http://xsc.github.io/kithara/kithara.core.html#var-with-server-named-queue[`with-server-named-queue`]
and
http://xsc.github.io/kithara/kithara.core.html#var-with-durable-queue[`with-durable-queue`].

[[common-messaging-patterns]]
== Common Messaging Patterns

Kithara aims to provide easily usable implementations for common messaging
patterns and scenarios.

[[dead-letter-backoff]]
=== Backoff via Dead-Letter-Queues

The namespace http://xsc.github.io/kithara/kithara.patterns.dead-letter-backoff.html[`kithara.patterns.dead-letter-backoff`]
contains two wrappers `with-dead-letter-backoff` and
`with-durable-dead-letter-backoff` providing delayed requeuing of messages by
dispatching them to a secondary queue, the "dead letter queue", from which it'll
eventually be republished. Both wrappers have to be applied after `with-queue`.

The simplest version infers names of additional exchanges/queues using the
original consumer queue:

[source,clojure]
----
(require '[kithara.patterns.dead-letter-backoff :as dlx])

(defonce rabbitmq-consumer-with-backoff
  (-> (rabbitmq/consumer ...)
      (dlx/with-dead-letter-backoff)
      (rabbitmq/with-queue ...)
      ...))
----

Additional options can be given - see the docstring of
`with-dead-letter-backoff` for a detailed overview.

[[lower-level-api]]
== Lower-Level RabbitMQ API

Kithara wraps the official Java RabbitMQ client - but only as far as necessary
to build consumers (and patterns). You can access those functions using
the `kithara.rabbitmq.*` namespaces as outlined in the respective
http://xsc.github.io/kithara/rabbitmq/index.html[auto-generated documentation].

[[contributing]]
== Contributing

Contributions are always welcome!

1. Create a new branch where you apply your changes (ideally also adding tests).
2. Make sure existing tests are passing.
3. Open a Pull Request on Github.

[[license]]
== License

....
The MIT License (MIT)

Copyright (c) 2016 Yannick Scherer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
....
