[[kithara]]
= kithara image:https://travis-ci.org/xsc/kithara.svg?branch=master["Build Status", link="https://travis-ci.org/xsc/kithara"]
:toc: macro
:toc-title:
:toclevels: 3

*kithara* is a (limited) https://www.rabbitmq.com[RabbitMQ] client for Clojure,
based on https://github.com/jhalterman/lyra[Lyra]. Its specific scope - and
thus source of its limitations - is the simple creation of RabbitMQ-based
 consumers with appropriate recovery and retry facilities.

If you're looking for a more complete RabbitMQ library you should check out
https://github.com/michaelklishin/langohr[langohr].

[[usage]]
== Usage

Coming soon.

== Table of Contents

toc::[]

[[quickstart]]
=== Quickstart

[source,clojure]
----
(require '[kithara.core :as rabbitmq]
         '[com.stuartsierra.component :as component])

(defonce rabbitmq-consumer
  (-> (rabbitmq/consumer
        (fn [{:keys [body]}]
          (println body))
        {:as :string})
      (rabbitmq/with-queue
        "my-queue"
        {:exchange     "my-exchange"
         :routing-keys ["*.print"]})
      (rabbitmq/with-channel
        {:prefetch-count 20})
      (rabbitmq/with-connection
        {:host "rabbitmq.my-cluster.com"})))

(alter-var-root #'rabbitmq-consumer component/start)
----

[[common-messaging-patterns]]
== Common Messaging Patterns

Kithara aims to provide easily usable implementations for common messaging
patterns and scenarios.

[[dead-letter-backoff]]
=== Backoff via Dead-Letter-Queues

The namespace http://xsc.github.io/kithara/kithara.patterns.dead-letter-backoff.html[`kithara.patterns.dead-letter-backoff`]
contains two wrappers `with-dead-letter-backoff` and
`with-durable-dead-letter-backoff` providing delayed requeuing of messages by
dispatching them to a secondary queue, the "dead letter queue", from which it'll
eventually be republished. Both wrappers have to be applied after `with-queue`.

The simplest version infers names of additional exchanges/queues using the
original consumer queue:

[source,clojure]
----
(require '[kithara.patterns.dead-letter-backoff :as dlx])

(defonce rabbitmq-consumer-with-backoff
  (-> (rabbitmq/consumer ...)
      (dlx/with-dead-letter-backoff)
      (rabbitmq/with-queue ...)
      ...))
----

Additional options can be given - see the docstring of
`with-dead-letter-backoff` for a detailed overview.

[[lower-level-api]]
== Lower-Level RabbitMQ API

Kithara wraps the official Java RabbitMQ client - but only as far as necessary
to build consumers (and patterns). You can access those functions using
the `kithara.rabbitmq.*` namespaces as outlined in the respective
http://xsc.github.io/kithara/rabbitmq/index.html[auto-generated documentation].

[[contributing]]
== Contributing

Contributions are always welcome!

1. Create a new branch where you apply your changes (ideally also adding tests).
2. Make sure existing tests are passing.
3. Open a Pull Request on Github.

[[license]]
== License

....
The MIT License (MIT)

Copyright (c) 2016 Yannick Scherer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
....
